export default [
  {
    addressType: 'SHIPPING',
    label: '1666784505038',
    street1: 'Test Address',
    city: ' Test',
    state: 'AK',
    postalCode: '12312',
    sourceSystem: 'RWD_MBR',
    street2: null,
    country: 'US',
    careOfFirstName: 'Test',
    careOfLastName: 'Test',
    careOfMiddleName: null,
    preferredIn: false,
    creationDate: '2022-10-26',
  },
  {
    addressType: 'SHIPPING',
    label: '1666784547939',
    street1: 'askjdh',
    city: 'asd',
    state: 'AK',
    postalCode: '12312',
    sourceSystem: 'RWD_MBR',
    street2: null,
    country: 'US',
    careOfFirstName: 'TEST',
    careOfLastName: 'asdkjh',
    careOfMiddleName: null,
    preferredIn: true,
    creationDate: '2022-10-26',
  },
  {
    addressType: 'SHIPPING',
    label: '1665671426258',
    street1: '1600 ETHAN WAY',
    city: 'SACRAMENTO',
    state: 'CA',
    postalCode: '95825',
    sourceSystem: 'RWD_MBR',
    street2: null,
    country: 'US',
    careOfFirstName: 'WPPMRNGBICEEFECAFN',
    careOfLastName: 'HCOTMRNHBJAIIFFEDLN',
    careOfMiddleName: null,
    preferredIn: false,
    creationDate: '2022-10-13',
  },
  {
    addressType: 'SHIPPING',
    label: '1665671426258',
    street1: '1600 ETHAN WAY',
    city: 'SACRAMENTO',
    state: 'CA',
    postalCode: '95825',
    sourceSystem: 'RWD_MBR',
    street2: null,
    country: 'US',
    careOfFirstName: 'WPPMRNGBICEEFECAFN',
    careOfLastName: 'HCOTMRNHBJAIIFFEDLN',
    careOfMiddleName: null,
    preferredIn: false,
    creationDate: '2022-10-13',
  },
];
